### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by danyeaw** [szymonkaliski/DAS-UI#1]
Without a license, I can copy or fork your repo, but I have no permission to use, modify, or share the software. Could you please add a license? Thanks!

[https://choosealicense.com](url)

**Comment by szymonkaliski** [comment]
Oh, forgot to add the LICENSE file, here it is https://github.com/szymonkaliski/DAS-UI/blob/master/LICENSE.md (MIT)

Thanks!
