### ISSUE TITLE
This is the most brilliant and frustrating idea!

### ISSUE THREAD

**Issue by MacroMachines** [szymonkaliski/DAS-UI#2]
I love the aesthetic, the keyboard concept and what you are going for, but intuitively I want to do certain things with the mouse from habit, because I am trained from 20 years of node patching to use the mouse and when I try to adjust something in here it pulls me to the brink of insanity! :P

This could be quite profound in tandem with the mouse based workflow techniques from your other work.

I just got invited to the beta test of cables.gl last month, I think you would find this interesting and potentially have some useful ideas.  I was actually just looking back at your SDF-UI as I am making some similar nodes in cables right now.

**Comment by szymonkaliski** [comment]
Haha, yeah, this was made mostly to see if making keyboard-only patching UI is possible (and looks like it is), but I wouldn't use it to make anything complex. 

My long-term idea would be to combine this, with some ideas from sdf-ui, and some other things bouncing around my head at some point in the future (maybe).
